### ISSUE TITLE
VR support for app, to see where the bus is at currently.

### ISSUE THREAD

**Issue by Camology** [yeSpud/MACSTransitApp#15]
**Add ability to use VR to view the route from the front as if you are the bus, so you know where it is.**

**Comment by yeSpud** [comment]
Can be done on phone via [Google Cardboard](https://arvr.google.com/cardboard/)

This may actually be doable 🤔

**Comment by yeSpud** [comment]
Because there is a charge for the use of google's street view service api this feature request will not be completed in this implementation.

The code for the feature will still be included in the event that someone would like to use it with their own api key, but consider the feature deprecated for this specific project. 

https://stackoverflow.com/questions/57739472/how-to-resolve-the-google-maps-android-api-street-view-service-has-been-disable

https://developers.google.com/maps/billing/gmp-billing?hl=en_US#dynamic-street-view
